Plane from trace
ucgmsim/source_modelling pull request #17
Opened 2024-12-04 01:39 UTC by claudio525

Build on top of #14, so that needs to be merged first.

- Adds function to create a Plane object from a fault trace definition. Useful for the old NSHM fault definitions.
- Increase tolerance in orientation check to prevent flipping when dip is very close to 90 (https://github.com/ucgmsim/source_modelling/blob/d22d5f08781bebd3410c1894d49503916801c74c/source_modelling/sources.py#L286)

2025-01-28 19:26 UTC, claudio525 commented
The latest commit has two changes:
- The order of the trace points is no longer important. The dip direction is used to determine the strike, which is all handled by the post_init.
- It now operates on nztm data instead of lat,lon to ensure a consistent dip direction, which is required for creating a Fault object.

2025-01-28 21:55 UTC, lispandfound requested changes

2025-01-28 21:55 UTC, lispandfound commented on tests/test_sources.py
> +    )
Similarly here, you should (and I don't currently) use `np.testing.assert_array_almost_equal` for better test failure outputs.

```suggestion
    assert shapely.get_coordinates(plane.geometry, include_z=True)[:-1] == pytest.approx(plane.bounds)
```

2025-01-28 22:09 UTC, lispandfound requested changes

2025-01-28 22:09 UTC, lispandfound commented on source_modelling/sources.py
> +             as great circle bearing.
Also this needs to be updated. Similar to `Plane.from_centroid_strike_dip`, it would be good to have both `dip_dir` and `dip_dir_nztm` where `dip_dir` is converted to nztm immediately.

2025-01-29 18:24 UTC, claudio525 commented
@lispandfound I was working on this last night and this morning without realising that you had made changes, so have just combined our changes.

2025-01-30 01:38 UTC, lispandfound commented
@claudio525 I made a couple of changes:

1. I move the dip direction check to after the plane rearrangement for strike. For really long faults (such as the alpine fault), dip direction is not quite consistent because it's a measured bearing from north and **the relative location of north** changes ever so slightly over really like faults -- like the Alpine fault for example. Now dip direction is checked after rearranging the planes into a line, and then only adjacent faults are checked. This is the only way I've been able to get the alpine fault nshm examples to load properly.

2025-02-02 22:40 UTC, lispandfound requested changes
Only one small change left!

2025-02-02 22:40 UTC, lispandfound commented on source_modelling/sources.py
> +
Is this still required?? this doesn't seem correct to me.

2025-02-03 01:37 UTC, lispandfound approved these changes

2025-02-03 20:45 UTC, sungeunbae commented on source_modelling/sources.py
> +            raise ValueError("Must supply at most one of dip_dir or dip_dir_nztm.")
```suggestion
            raise ValueError("Must supply at least one of dip_dir or dip_dir_nztm.")
```

2025-02-03 20:53 UTC, joelridden commented on tests/test_sources.py
> +def nztm_coordinate(y: float, x: float, depth: Optional[float] = None) -> np.ndarray:
Is this being used?

2025-02-03 20:55 UTC, AndrewRidden-Harper approved these changes

2025-02-03 20:59 UTC, sungeunbae commented on tests/test_sources.py
> +    assert pytest.approx(plane.top_m, abs=1e-3) == dtop * 1000
The value of abs varies from 1e-6 (strike_nztm, dip)  to 10 (dip_dir). Was it determined empirically?

2025-02-03 21:55 UTC, lispandfound approved these changes

2025-02-03 21:55 UTC, lispandfound commented on tests/test_sources.py
> +    assert pytest.approx(plane.top_m, abs=1e-3) == dtop * 1000
> The value of abs varies from 1e-6 (strike_nztm, dip) to 10 (dip_dir). Was it determined empirically?

The tolerance on dip direction is 0.1. Yes some of these values have higher tolerances because they are subject to greater variation and numerical error. The great circle bearings in particular are very finicky to get right.

2025-02-03 21:55 UTC, lispandfound commented on tests/test_sources.py
> +def nztm_coordinate(y: float, x: float, depth: Optional[float] = None) -> np.ndarray:
No. I'll remove it.

2025-02-03 21:56 UTC, joelridden approved these changes

2025-02-04 03:24 UTC, sungeunbae approved these changes

2025-02-04 03:39 UTC, merged